# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


url: "https://cmorrow.github.io"
baseurl: ''

# Site settings
title: Chris Morrow
email: chris@chrisjmorrow.com
description: > # this means to ignore newlines until "baseurl:"
  This site is aimed to be a small way to share my lessons learned in web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chrisjmorrow.com" # the base hostname & protocol for your site
twitter_username: _ChrisMorrow
github_username:  cmorrow

post:
  template: _post.txt
  extension: md

page:
  template: _page.txt
  extension: md

editor: subl

# Build settings
markdown: kramdown

# Server settings
livereload: true    # You no longer need to include --livereload

# exclude directories
exclude: ['_src',
          'script',
          'gulpfile.js', 
          'vendor',
          'Gemfile',
          'Gemfile.lock',
          'node_modules',
          'package.json',
          'Rakefile',
          'README.md']
